const styles = {
  page: { maxWidth: 640, margin: '0 auto', padding: '32px 24px 96px', display: 'flex', flexDirection: 'column', gap: 24 },
  h1: { fontSize: 20, margin: 0 },
  h2: { fontSize: 15, margin: '0 0 4px' },
  subtitle: { fontSize: 13, color: '#666', margin: 0 },
  section: {
    background: '#fff',
    border: '1px solid #eee',
    borderRadius: 12,
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  hint: { fontSize: 12, color: '#888', margin: 0 },
  warning: { fontSize: 12, color: '#9a6700', margin: 0 },
  success: { fontSize: 12, color: '#1a7f37', fontWeight: 600, margin: 0 },
  processing: {
    fontSize: 13,
    fontWeight: 600,
    color: '#1a1a1a',
    background: '#f2f2f2',
    padding: '10px 12px',
    borderRadius: 8,
    margin: 0,
  },
  row: { display: 'flex', gap: 8, alignItems: 'center' },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  input: {
    flex: 1,
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #ddd',
    fontSize: 13,
    fontFamily: 'inherit',
  },
  inputMissing: { border: '1px solid #d97706', background: '#fffaf0' },
  textarea: {
    width: '100%',
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #ddd',
    fontSize: 13,
    fontFamily: 'inherit',
    minHeight: 60,
    resize: 'vertical',
    boxSizing: 'border-box',
  },
  button: {
    padding: '8px 14px',
    borderRadius: 8,
    border: 'none',
    background: '#1a1a1a',
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  buttonSecondary: {
    padding: '6px 10px',
    borderRadius: 8,
    border: '1px solid #ddd',
    background: '#fff',
    color: '#1a1a1a',
    fontSize: 12,
    cursor: 'pointer',
  },
  buttonDisabled: { opacity: 0.5, cursor: 'not-allowed' },
  readonlyItem: { fontSize: 12, flex: 1 },
  stickyFooter: {
    position: 'sticky',
    bottom: 0,
    background: '#fafafa',
    padding: '12px 0',
    display: 'flex',
    gap: 12,
    alignItems: 'center',
  },
  itemCard: {
    border: '1px solid #eee',
    borderRadius: 8,
    padding: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
}

export default styles
